package dev.lpsmods.morepumpkins.core;

import dev.lpsmods.morepumpkins.Constants;
import dev.lpsmods.morepumpkins.block.EquipableCarvedPumpkinBlock;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockBehaviour;

/**
 * Author: legopitstop
 */
public class ModBlocks {
    // Soul Jack o' Lantern
    public static final Block SOUL_JACK_O_LANTERN;
    public static final Block CREEPER_SOUL_JACK_O_LANTERN;
    public static final Block FLOWER_SOUL_JACK_O_LANTERN;
    public static final Block GHAST_SOUL_JACK_O_LANTERN;
    public static final Block GLOBE_SOUL_JACK_O_LANTERN;
    public static final Block OBSERVER_SOUL_JACK_O_LANTERN;
    public static final Block SKELETON_SOUL_JACK_O_LANTERN;
    public static final Block SNOUT_SOUL_JACK_O_LANTERN;
    public static final Block ZERO_SOUL_JACK_O_LANTERN;
    public static final Block ONE_SOUL_JACK_O_LANTERN;
    public static final Block TWO_SOUL_JACK_O_LANTERN;
    public static final Block THREE_SOUL_JACK_O_LANTERN;
    public static final Block FOUR_SOUL_JACK_O_LANTERN;
    public static final Block FIVE_SOUL_JACK_O_LANTERN;
    public static final Block SIX_SOUL_JACK_O_LANTERN;
    public static final Block SEVEN_SOUL_JACK_O_LANTERN;
    public static final Block EIGHT_SOUL_JACK_O_LANTERN;
    public static final Block NINE_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_A_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_B_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_C_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_D_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_E_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_F_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_G_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_H_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_I_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_J_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_K_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_L_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_M_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_N_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_O_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_P_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_Q_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_R_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_S_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_T_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_U_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_V_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_W_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_X_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_Y_SOUL_JACK_O_LANTERN;
    public static final Block LOWERCASE_Z_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_A_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_B_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_C_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_D_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_E_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_F_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_G_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_H_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_I_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_J_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_K_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_L_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_M_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_N_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_O_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_P_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_Q_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_R_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_S_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_T_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_U_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_V_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_W_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_X_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_Y_SOUL_JACK_O_LANTERN;
    public static final Block UPPERCASE_Z_SOUL_JACK_O_LANTERN;

    // Jack o' Lantern
    public static final Block CREEPER_JACK_O_LANTERN;
    public static final Block FLOWER_JACK_O_LANTERN;
    public static final Block GHAST_JACK_O_LANTERN;
    public static final Block GLOBE_JACK_O_LANTERN;
    public static final Block OBSERVER_JACK_O_LANTERN;
    public static final Block SKELETON_JACK_O_LANTERN;
    public static final Block SNOUT_JACK_O_LANTERN;
    public static final Block ZERO_JACK_O_LANTERN;
    public static final Block ONE_JACK_O_LANTERN;
    public static final Block TWO_JACK_O_LANTERN;
    public static final Block THREE_JACK_O_LANTERN;
    public static final Block FOUR_JACK_O_LANTERN;
    public static final Block FIVE_JACK_O_LANTERN;
    public static final Block SIX_JACK_O_LANTERN;
    public static final Block SEVEN_JACK_O_LANTERN;
    public static final Block EIGHT_JACK_O_LANTERN;
    public static final Block NINE_JACK_O_LANTERN;
    public static final Block LOWERCASE_A_JACK_O_LANTERN;
    public static final Block LOWERCASE_B_JACK_O_LANTERN;
    public static final Block LOWERCASE_C_JACK_O_LANTERN;
    public static final Block LOWERCASE_D_JACK_O_LANTERN;
    public static final Block LOWERCASE_E_JACK_O_LANTERN;
    public static final Block LOWERCASE_F_JACK_O_LANTERN;
    public static final Block LOWERCASE_G_JACK_O_LANTERN;
    public static final Block LOWERCASE_H_JACK_O_LANTERN;
    public static final Block LOWERCASE_I_JACK_O_LANTERN;
    public static final Block LOWERCASE_J_JACK_O_LANTERN;
    public static final Block LOWERCASE_K_JACK_O_LANTERN;
    public static final Block LOWERCASE_L_JACK_O_LANTERN;
    public static final Block LOWERCASE_M_JACK_O_LANTERN;
    public static final Block LOWERCASE_N_JACK_O_LANTERN;
    public static final Block LOWERCASE_O_JACK_O_LANTERN;
    public static final Block LOWERCASE_P_JACK_O_LANTERN;
    public static final Block LOWERCASE_Q_JACK_O_LANTERN;
    public static final Block LOWERCASE_R_JACK_O_LANTERN;
    public static final Block LOWERCASE_S_JACK_O_LANTERN;
    public static final Block LOWERCASE_T_JACK_O_LANTERN;
    public static final Block LOWERCASE_U_JACK_O_LANTERN;
    public static final Block LOWERCASE_V_JACK_O_LANTERN;
    public static final Block LOWERCASE_W_JACK_O_LANTERN;
    public static final Block LOWERCASE_X_JACK_O_LANTERN;
    public static final Block LOWERCASE_Y_JACK_O_LANTERN;
    public static final Block LOWERCASE_Z_JACK_O_LANTERN;
    public static final Block UPPERCASE_A_JACK_O_LANTERN;
    public static final Block UPPERCASE_B_JACK_O_LANTERN;
    public static final Block UPPERCASE_C_JACK_O_LANTERN;
    public static final Block UPPERCASE_D_JACK_O_LANTERN;
    public static final Block UPPERCASE_E_JACK_O_LANTERN;
    public static final Block UPPERCASE_F_JACK_O_LANTERN;
    public static final Block UPPERCASE_G_JACK_O_LANTERN;
    public static final Block UPPERCASE_H_JACK_O_LANTERN;
    public static final Block UPPERCASE_I_JACK_O_LANTERN;
    public static final Block UPPERCASE_J_JACK_O_LANTERN;
    public static final Block UPPERCASE_K_JACK_O_LANTERN;
    public static final Block UPPERCASE_L_JACK_O_LANTERN;
    public static final Block UPPERCASE_M_JACK_O_LANTERN;
    public static final Block UPPERCASE_N_JACK_O_LANTERN;
    public static final Block UPPERCASE_O_JACK_O_LANTERN;
    public static final Block UPPERCASE_P_JACK_O_LANTERN;
    public static final Block UPPERCASE_Q_JACK_O_LANTERN;
    public static final Block UPPERCASE_R_JACK_O_LANTERN;
    public static final Block UPPERCASE_S_JACK_O_LANTERN;
    public static final Block UPPERCASE_T_JACK_O_LANTERN;
    public static final Block UPPERCASE_U_JACK_O_LANTERN;
    public static final Block UPPERCASE_V_JACK_O_LANTERN;
    public static final Block UPPERCASE_W_JACK_O_LANTERN;
    public static final Block UPPERCASE_X_JACK_O_LANTERN;
    public static final Block UPPERCASE_Y_JACK_O_LANTERN;
    public static final Block UPPERCASE_Z_JACK_O_LANTERN;

    // Carved Pumpkin
    public static final Block CREEPER_CARVED_PUMPKIN;
    public static final Block FLOWER_CARVED_PUMPKIN;
    public static final Block GHAST_CARVED_PUMPKIN;
    public static final Block GLOBE_CARVED_PUMPKIN;
    public static final Block OBSERVER_CARVED_PUMPKIN;
    public static final Block SKELETON_CARVED_PUMPKIN;
    public static final Block SNOUT_CARVED_PUMPKIN;
    public static final Block ZERO_CARVED_PUMPKIN;
    public static final Block ONE_CARVED_PUMPKIN;
    public static final Block TWO_CARVED_PUMPKIN;
    public static final Block THREE_CARVED_PUMPKIN;
    public static final Block FOUR_CARVED_PUMPKIN;
    public static final Block FIVE_CARVED_PUMPKIN;
    public static final Block SIX_CARVED_PUMPKIN;
    public static final Block SEVEN_CARVED_PUMPKIN;
    public static final Block EIGHT_CARVED_PUMPKIN;
    public static final Block NINE_CARVED_PUMPKIN;
    public static final Block LOWERCASE_A_CARVED_PUMPKIN;
    public static final Block LOWERCASE_B_CARVED_PUMPKIN;
    public static final Block LOWERCASE_C_CARVED_PUMPKIN;
    public static final Block LOWERCASE_D_CARVED_PUMPKIN;
    public static final Block LOWERCASE_E_CARVED_PUMPKIN;
    public static final Block LOWERCASE_F_CARVED_PUMPKIN;
    public static final Block LOWERCASE_G_CARVED_PUMPKIN;
    public static final Block LOWERCASE_H_CARVED_PUMPKIN;
    public static final Block LOWERCASE_I_CARVED_PUMPKIN;
    public static final Block LOWERCASE_J_CARVED_PUMPKIN;
    public static final Block LOWERCASE_K_CARVED_PUMPKIN;
    public static final Block LOWERCASE_L_CARVED_PUMPKIN;
    public static final Block LOWERCASE_M_CARVED_PUMPKIN;
    public static final Block LOWERCASE_N_CARVED_PUMPKIN;
    public static final Block LOWERCASE_O_CARVED_PUMPKIN;
    public static final Block LOWERCASE_P_CARVED_PUMPKIN;
    public static final Block LOWERCASE_Q_CARVED_PUMPKIN;
    public static final Block LOWERCASE_R_CARVED_PUMPKIN;
    public static final Block LOWERCASE_S_CARVED_PUMPKIN;
    public static final Block LOWERCASE_T_CARVED_PUMPKIN;
    public static final Block LOWERCASE_U_CARVED_PUMPKIN;
    public static final Block LOWERCASE_V_CARVED_PUMPKIN;
    public static final Block LOWERCASE_W_CARVED_PUMPKIN;
    public static final Block LOWERCASE_X_CARVED_PUMPKIN;
    public static final Block LOWERCASE_Y_CARVED_PUMPKIN;
    public static final Block LOWERCASE_Z_CARVED_PUMPKIN;
    public static final Block UPPERCASE_A_CARVED_PUMPKIN;
    public static final Block UPPERCASE_B_CARVED_PUMPKIN;
    public static final Block UPPERCASE_C_CARVED_PUMPKIN;
    public static final Block UPPERCASE_D_CARVED_PUMPKIN;
    public static final Block UPPERCASE_E_CARVED_PUMPKIN;
    public static final Block UPPERCASE_F_CARVED_PUMPKIN;
    public static final Block UPPERCASE_G_CARVED_PUMPKIN;
    public static final Block UPPERCASE_H_CARVED_PUMPKIN;
    public static final Block UPPERCASE_I_CARVED_PUMPKIN;
    public static final Block UPPERCASE_J_CARVED_PUMPKIN;
    public static final Block UPPERCASE_K_CARVED_PUMPKIN;
    public static final Block UPPERCASE_L_CARVED_PUMPKIN;
    public static final Block UPPERCASE_M_CARVED_PUMPKIN;
    public static final Block UPPERCASE_N_CARVED_PUMPKIN;
    public static final Block UPPERCASE_O_CARVED_PUMPKIN;
    public static final Block UPPERCASE_P_CARVED_PUMPKIN;
    public static final Block UPPERCASE_Q_CARVED_PUMPKIN;
    public static final Block UPPERCASE_R_CARVED_PUMPKIN;
    public static final Block UPPERCASE_S_CARVED_PUMPKIN;
    public static final Block UPPERCASE_T_CARVED_PUMPKIN;
    public static final Block UPPERCASE_U_CARVED_PUMPKIN;
    public static final Block UPPERCASE_V_CARVED_PUMPKIN;
    public static final Block UPPERCASE_W_CARVED_PUMPKIN;
    public static final Block UPPERCASE_X_CARVED_PUMPKIN;
    public static final Block UPPERCASE_Y_CARVED_PUMPKIN;
    public static final Block UPPERCASE_Z_CARVED_PUMPKIN;

    private static Block registerBlock(String name, Block block) {
        return Registry.register(BuiltInRegistries.BLOCK, ResourceLocation.fromNamespaceAndPath(Constants.MOD_ID, name), block);
    }

    private static Block createJackOLantern() {
        return new EquipableCarvedPumpkinBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
    }

    private static Block createCarvedPumpkin() {
        return new EquipableCarvedPumpkinBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
    }

    public static void init() {}

    static {
        SOUL_JACK_O_LANTERN = registerBlock("soul_jack_o_lantern", createJackOLantern());
        CREEPER_SOUL_JACK_O_LANTERN = registerBlock("creeper_soul_jack_o_lantern", createJackOLantern());
        FLOWER_SOUL_JACK_O_LANTERN = registerBlock("flower_soul_jack_o_lantern", createJackOLantern());
        GHAST_SOUL_JACK_O_LANTERN = registerBlock("ghast_soul_jack_o_lantern", createJackOLantern());
        GLOBE_SOUL_JACK_O_LANTERN = registerBlock("globe_soul_jack_o_lantern", createJackOLantern());
        OBSERVER_SOUL_JACK_O_LANTERN = registerBlock("observer_soul_jack_o_lantern", createJackOLantern());
        SKELETON_SOUL_JACK_O_LANTERN = registerBlock("skeleton_soul_jack_o_lantern", createJackOLantern());
        SNOUT_SOUL_JACK_O_LANTERN = registerBlock("snout_soul_jack_o_lantern", createJackOLantern());
        ZERO_SOUL_JACK_O_LANTERN = registerBlock("zero_soul_jack_o_lantern", createJackOLantern());
        ONE_SOUL_JACK_O_LANTERN = registerBlock("one_soul_jack_o_lantern", createJackOLantern());
        TWO_SOUL_JACK_O_LANTERN = registerBlock("two_soul_jack_o_lantern", createJackOLantern());
        THREE_SOUL_JACK_O_LANTERN = registerBlock("three_soul_jack_o_lantern", createJackOLantern());
        FOUR_SOUL_JACK_O_LANTERN = registerBlock("four_soul_jack_o_lantern", createJackOLantern());
        FIVE_SOUL_JACK_O_LANTERN = registerBlock("five_soul_jack_o_lantern", createJackOLantern());
        SIX_SOUL_JACK_O_LANTERN = registerBlock("six_soul_jack_o_lantern", createJackOLantern());
        SEVEN_SOUL_JACK_O_LANTERN = registerBlock("seven_soul_jack_o_lantern", createJackOLantern());
        EIGHT_SOUL_JACK_O_LANTERN = registerBlock("eight_soul_jack_o_lantern", createJackOLantern());
        NINE_SOUL_JACK_O_LANTERN = registerBlock("nine_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_A_SOUL_JACK_O_LANTERN = registerBlock("lowercase_a_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_B_SOUL_JACK_O_LANTERN = registerBlock("lowercase_b_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_C_SOUL_JACK_O_LANTERN = registerBlock("lowercase_c_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_D_SOUL_JACK_O_LANTERN = registerBlock("lowercase_d_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_E_SOUL_JACK_O_LANTERN = registerBlock("lowercase_e_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_F_SOUL_JACK_O_LANTERN = registerBlock("lowercase_f_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_G_SOUL_JACK_O_LANTERN = registerBlock("lowercase_g_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_H_SOUL_JACK_O_LANTERN = registerBlock("lowercase_h_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_I_SOUL_JACK_O_LANTERN = registerBlock("lowercase_i_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_J_SOUL_JACK_O_LANTERN = registerBlock("lowercase_j_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_K_SOUL_JACK_O_LANTERN = registerBlock("lowercase_k_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_L_SOUL_JACK_O_LANTERN = registerBlock("lowercase_l_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_M_SOUL_JACK_O_LANTERN = registerBlock("lowercase_m_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_N_SOUL_JACK_O_LANTERN = registerBlock("lowercase_n_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_O_SOUL_JACK_O_LANTERN = registerBlock("lowercase_o_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_P_SOUL_JACK_O_LANTERN = registerBlock("lowercase_p_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_Q_SOUL_JACK_O_LANTERN = registerBlock("lowercase_q_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_R_SOUL_JACK_O_LANTERN = registerBlock("lowercase_r_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_S_SOUL_JACK_O_LANTERN = registerBlock("lowercase_s_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_T_SOUL_JACK_O_LANTERN = registerBlock("lowercase_t_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_U_SOUL_JACK_O_LANTERN = registerBlock("lowercase_u_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_V_SOUL_JACK_O_LANTERN = registerBlock("lowercase_v_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_W_SOUL_JACK_O_LANTERN = registerBlock("lowercase_w_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_X_SOUL_JACK_O_LANTERN = registerBlock("lowercase_x_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_Y_SOUL_JACK_O_LANTERN = registerBlock("lowercase_y_soul_jack_o_lantern", createJackOLantern());
        LOWERCASE_Z_SOUL_JACK_O_LANTERN = registerBlock("lowercase_z_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_A_SOUL_JACK_O_LANTERN = registerBlock("uppercase_a_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_B_SOUL_JACK_O_LANTERN = registerBlock("uppercase_b_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_C_SOUL_JACK_O_LANTERN = registerBlock("uppercase_c_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_D_SOUL_JACK_O_LANTERN = registerBlock("uppercase_d_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_E_SOUL_JACK_O_LANTERN = registerBlock("uppercase_e_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_F_SOUL_JACK_O_LANTERN = registerBlock("uppercase_f_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_G_SOUL_JACK_O_LANTERN = registerBlock("uppercase_g_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_H_SOUL_JACK_O_LANTERN = registerBlock("uppercase_h_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_I_SOUL_JACK_O_LANTERN = registerBlock("uppercase_i_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_J_SOUL_JACK_O_LANTERN = registerBlock("uppercase_j_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_K_SOUL_JACK_O_LANTERN = registerBlock("uppercase_k_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_L_SOUL_JACK_O_LANTERN = registerBlock("uppercase_l_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_M_SOUL_JACK_O_LANTERN = registerBlock("uppercase_m_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_N_SOUL_JACK_O_LANTERN = registerBlock("uppercase_n_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_O_SOUL_JACK_O_LANTERN = registerBlock("uppercase_o_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_P_SOUL_JACK_O_LANTERN = registerBlock("uppercase_p_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_Q_SOUL_JACK_O_LANTERN = registerBlock("uppercase_q_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_R_SOUL_JACK_O_LANTERN = registerBlock("uppercase_r_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_S_SOUL_JACK_O_LANTERN = registerBlock("uppercase_s_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_T_SOUL_JACK_O_LANTERN = registerBlock("uppercase_t_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_U_SOUL_JACK_O_LANTERN = registerBlock("uppercase_u_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_V_SOUL_JACK_O_LANTERN = registerBlock("uppercase_v_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_W_SOUL_JACK_O_LANTERN = registerBlock("uppercase_w_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_X_SOUL_JACK_O_LANTERN = registerBlock("uppercase_x_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_Y_SOUL_JACK_O_LANTERN = registerBlock("uppercase_y_soul_jack_o_lantern", createJackOLantern());
        UPPERCASE_Z_SOUL_JACK_O_LANTERN = registerBlock("uppercase_z_soul_jack_o_lantern", createJackOLantern());
        CREEPER_JACK_O_LANTERN = registerBlock("creeper_jack_o_lantern", createJackOLantern());
        FLOWER_JACK_O_LANTERN = registerBlock("flower_jack_o_lantern", createJackOLantern());
        GHAST_JACK_O_LANTERN = registerBlock("ghast_jack_o_lantern", createJackOLantern());
        GLOBE_JACK_O_LANTERN = registerBlock("globe_jack_o_lantern", createJackOLantern());
        OBSERVER_JACK_O_LANTERN = registerBlock("observer_jack_o_lantern", createJackOLantern());
        SKELETON_JACK_O_LANTERN = registerBlock("skeleton_jack_o_lantern", createJackOLantern());
        SNOUT_JACK_O_LANTERN = registerBlock("snout_jack_o_lantern", createJackOLantern());
        ZERO_JACK_O_LANTERN = registerBlock("zero_jack_o_lantern", createJackOLantern());
        ONE_JACK_O_LANTERN = registerBlock("one_jack_o_lantern", createJackOLantern());
        TWO_JACK_O_LANTERN = registerBlock("two_jack_o_lantern", createJackOLantern());
        THREE_JACK_O_LANTERN = registerBlock("three_jack_o_lantern", createJackOLantern());
        FOUR_JACK_O_LANTERN = registerBlock("four_jack_o_lantern", createJackOLantern());
        FIVE_JACK_O_LANTERN = registerBlock("five_jack_o_lantern", createJackOLantern());
        SIX_JACK_O_LANTERN = registerBlock("six_jack_o_lantern", createJackOLantern());
        SEVEN_JACK_O_LANTERN = registerBlock("seven_jack_o_lantern", createJackOLantern());
        EIGHT_JACK_O_LANTERN = registerBlock("eight_jack_o_lantern", createJackOLantern());
        NINE_JACK_O_LANTERN = registerBlock("nine_jack_o_lantern", createJackOLantern());
        LOWERCASE_A_JACK_O_LANTERN = registerBlock("lowercase_a_jack_o_lantern", createJackOLantern());
        LOWERCASE_B_JACK_O_LANTERN = registerBlock("lowercase_b_jack_o_lantern", createJackOLantern());
        LOWERCASE_C_JACK_O_LANTERN = registerBlock("lowercase_c_jack_o_lantern", createJackOLantern());
        LOWERCASE_D_JACK_O_LANTERN = registerBlock("lowercase_d_jack_o_lantern", createJackOLantern());
        LOWERCASE_E_JACK_O_LANTERN = registerBlock("lowercase_e_jack_o_lantern", createJackOLantern());
        LOWERCASE_F_JACK_O_LANTERN = registerBlock("lowercase_f_jack_o_lantern", createJackOLantern());
        LOWERCASE_G_JACK_O_LANTERN = registerBlock("lowercase_g_jack_o_lantern", createJackOLantern());
        LOWERCASE_H_JACK_O_LANTERN = registerBlock("lowercase_h_jack_o_lantern", createJackOLantern());
        LOWERCASE_I_JACK_O_LANTERN = registerBlock("lowercase_i_jack_o_lantern", createJackOLantern());
        LOWERCASE_J_JACK_O_LANTERN = registerBlock("lowercase_j_jack_o_lantern", createJackOLantern());
        LOWERCASE_K_JACK_O_LANTERN = registerBlock("lowercase_k_jack_o_lantern", createJackOLantern());
        LOWERCASE_L_JACK_O_LANTERN = registerBlock("lowercase_l_jack_o_lantern", createJackOLantern());
        LOWERCASE_M_JACK_O_LANTERN = registerBlock("lowercase_m_jack_o_lantern", createJackOLantern());
        LOWERCASE_N_JACK_O_LANTERN = registerBlock("lowercase_n_jack_o_lantern", createJackOLantern());
        LOWERCASE_O_JACK_O_LANTERN = registerBlock("lowercase_o_jack_o_lantern", createJackOLantern());
        LOWERCASE_P_JACK_O_LANTERN = registerBlock("lowercase_p_jack_o_lantern", createJackOLantern());
        LOWERCASE_Q_JACK_O_LANTERN = registerBlock("lowercase_q_jack_o_lantern", createJackOLantern());
        LOWERCASE_R_JACK_O_LANTERN = registerBlock("lowercase_r_jack_o_lantern", createJackOLantern());
        LOWERCASE_S_JACK_O_LANTERN = registerBlock("lowercase_s_jack_o_lantern", createJackOLantern());
        LOWERCASE_T_JACK_O_LANTERN = registerBlock("lowercase_t_jack_o_lantern", createJackOLantern());
        LOWERCASE_U_JACK_O_LANTERN = registerBlock("lowercase_u_jack_o_lantern", createJackOLantern());
        LOWERCASE_V_JACK_O_LANTERN = registerBlock("lowercase_v_jack_o_lantern", createJackOLantern());
        LOWERCASE_W_JACK_O_LANTERN = registerBlock("lowercase_w_jack_o_lantern", createJackOLantern());
        LOWERCASE_X_JACK_O_LANTERN = registerBlock("lowercase_x_jack_o_lantern", createJackOLantern());
        LOWERCASE_Y_JACK_O_LANTERN = registerBlock("lowercase_y_jack_o_lantern", createJackOLantern());
        LOWERCASE_Z_JACK_O_LANTERN = registerBlock("lowercase_z_jack_o_lantern", createJackOLantern());
        UPPERCASE_A_JACK_O_LANTERN = registerBlock("uppercase_a_jack_o_lantern", createJackOLantern());
        UPPERCASE_B_JACK_O_LANTERN = registerBlock("uppercase_b_jack_o_lantern", createJackOLantern());
        UPPERCASE_C_JACK_O_LANTERN = registerBlock("uppercase_c_jack_o_lantern", createJackOLantern());
        UPPERCASE_D_JACK_O_LANTERN = registerBlock("uppercase_d_jack_o_lantern", createJackOLantern());
        UPPERCASE_E_JACK_O_LANTERN = registerBlock("uppercase_e_jack_o_lantern", createJackOLantern());
        UPPERCASE_F_JACK_O_LANTERN = registerBlock("uppercase_f_jack_o_lantern", createJackOLantern());
        UPPERCASE_G_JACK_O_LANTERN = registerBlock("uppercase_g_jack_o_lantern", createJackOLantern());
        UPPERCASE_H_JACK_O_LANTERN = registerBlock("uppercase_h_jack_o_lantern", createJackOLantern());
        UPPERCASE_I_JACK_O_LANTERN = registerBlock("uppercase_i_jack_o_lantern", createJackOLantern());
        UPPERCASE_J_JACK_O_LANTERN = registerBlock("uppercase_j_jack_o_lantern", createJackOLantern());
        UPPERCASE_K_JACK_O_LANTERN = registerBlock("uppercase_k_jack_o_lantern", createJackOLantern());
        UPPERCASE_L_JACK_O_LANTERN = registerBlock("uppercase_l_jack_o_lantern", createJackOLantern());
        UPPERCASE_M_JACK_O_LANTERN = registerBlock("uppercase_m_jack_o_lantern", createJackOLantern());
        UPPERCASE_N_JACK_O_LANTERN = registerBlock("uppercase_n_jack_o_lantern", createJackOLantern());
        UPPERCASE_O_JACK_O_LANTERN = registerBlock("uppercase_o_jack_o_lantern", createJackOLantern());
        UPPERCASE_P_JACK_O_LANTERN = registerBlock("uppercase_p_jack_o_lantern", createJackOLantern());
        UPPERCASE_Q_JACK_O_LANTERN = registerBlock("uppercase_q_jack_o_lantern", createJackOLantern());
        UPPERCASE_R_JACK_O_LANTERN = registerBlock("uppercase_r_jack_o_lantern", createJackOLantern());
        UPPERCASE_S_JACK_O_LANTERN = registerBlock("uppercase_s_jack_o_lantern", createJackOLantern());
        UPPERCASE_T_JACK_O_LANTERN = registerBlock("uppercase_t_jack_o_lantern", createJackOLantern());
        UPPERCASE_U_JACK_O_LANTERN = registerBlock("uppercase_u_jack_o_lantern", createJackOLantern());
        UPPERCASE_V_JACK_O_LANTERN = registerBlock("uppercase_v_jack_o_lantern", createJackOLantern());
        UPPERCASE_W_JACK_O_LANTERN = registerBlock("uppercase_w_jack_o_lantern", createJackOLantern());
        UPPERCASE_X_JACK_O_LANTERN = registerBlock("uppercase_x_jack_o_lantern", createJackOLantern());
        UPPERCASE_Y_JACK_O_LANTERN = registerBlock("uppercase_y_jack_o_lantern", createJackOLantern());
        UPPERCASE_Z_JACK_O_LANTERN = registerBlock("uppercase_z_jack_o_lantern", createJackOLantern());
        CREEPER_CARVED_PUMPKIN = registerBlock("creeper_carved_pumpkin", createCarvedPumpkin());
        FLOWER_CARVED_PUMPKIN = registerBlock("flower_carved_pumpkin", createCarvedPumpkin());
        GHAST_CARVED_PUMPKIN = registerBlock("ghast_carved_pumpkin", createCarvedPumpkin());
        GLOBE_CARVED_PUMPKIN = registerBlock("globe_carved_pumpkin", createCarvedPumpkin());
        OBSERVER_CARVED_PUMPKIN = registerBlock("observer_carved_pumpkin", createCarvedPumpkin());
        SKELETON_CARVED_PUMPKIN = registerBlock("skeleton_carved_pumpkin", createCarvedPumpkin());
        SNOUT_CARVED_PUMPKIN = registerBlock("snout_carved_pumpkin", createCarvedPumpkin());
        ZERO_CARVED_PUMPKIN = registerBlock("zero_carved_pumpkin", createCarvedPumpkin());
        ONE_CARVED_PUMPKIN = registerBlock("one_carved_pumpkin", createCarvedPumpkin());
        TWO_CARVED_PUMPKIN = registerBlock("two_carved_pumpkin", createCarvedPumpkin());
        THREE_CARVED_PUMPKIN = registerBlock("three_carved_pumpkin", createCarvedPumpkin());
        FOUR_CARVED_PUMPKIN = registerBlock("four_carved_pumpkin", createCarvedPumpkin());
        FIVE_CARVED_PUMPKIN = registerBlock("five_carved_pumpkin", createCarvedPumpkin());
        SIX_CARVED_PUMPKIN = registerBlock("six_carved_pumpkin", createCarvedPumpkin());
        SEVEN_CARVED_PUMPKIN = registerBlock("seven_carved_pumpkin", createCarvedPumpkin());
        EIGHT_CARVED_PUMPKIN = registerBlock("eight_carved_pumpkin", createCarvedPumpkin());
        NINE_CARVED_PUMPKIN = registerBlock("nine_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_A_CARVED_PUMPKIN = registerBlock("lowercase_a_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_B_CARVED_PUMPKIN = registerBlock("lowercase_b_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_C_CARVED_PUMPKIN = registerBlock("lowercase_c_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_D_CARVED_PUMPKIN = registerBlock("lowercase_d_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_E_CARVED_PUMPKIN = registerBlock("lowercase_e_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_F_CARVED_PUMPKIN = registerBlock("lowercase_f_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_G_CARVED_PUMPKIN = registerBlock("lowercase_g_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_H_CARVED_PUMPKIN = registerBlock("lowercase_h_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_I_CARVED_PUMPKIN = registerBlock("lowercase_i_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_J_CARVED_PUMPKIN = registerBlock("lowercase_j_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_K_CARVED_PUMPKIN = registerBlock("lowercase_k_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_L_CARVED_PUMPKIN = registerBlock("lowercase_l_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_M_CARVED_PUMPKIN = registerBlock("lowercase_m_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_N_CARVED_PUMPKIN = registerBlock("lowercase_n_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_O_CARVED_PUMPKIN = registerBlock("lowercase_o_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_P_CARVED_PUMPKIN = registerBlock("lowercase_p_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_Q_CARVED_PUMPKIN = registerBlock("lowercase_q_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_R_CARVED_PUMPKIN = registerBlock("lowercase_r_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_S_CARVED_PUMPKIN = registerBlock("lowercase_s_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_T_CARVED_PUMPKIN = registerBlock("lowercase_t_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_U_CARVED_PUMPKIN = registerBlock("lowercase_u_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_V_CARVED_PUMPKIN = registerBlock("lowercase_v_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_W_CARVED_PUMPKIN = registerBlock("lowercase_w_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_X_CARVED_PUMPKIN = registerBlock("lowercase_x_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_Y_CARVED_PUMPKIN = registerBlock("lowercase_y_carved_pumpkin", createCarvedPumpkin());
        LOWERCASE_Z_CARVED_PUMPKIN = registerBlock("lowercase_z_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_A_CARVED_PUMPKIN = registerBlock("uppercase_a_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_B_CARVED_PUMPKIN = registerBlock("uppercase_b_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_C_CARVED_PUMPKIN = registerBlock("uppercase_c_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_D_CARVED_PUMPKIN = registerBlock("uppercase_d_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_E_CARVED_PUMPKIN = registerBlock("uppercase_e_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_F_CARVED_PUMPKIN = registerBlock("uppercase_f_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_G_CARVED_PUMPKIN = registerBlock("uppercase_g_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_H_CARVED_PUMPKIN = registerBlock("uppercase_h_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_I_CARVED_PUMPKIN = registerBlock("uppercase_i_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_J_CARVED_PUMPKIN = registerBlock("uppercase_j_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_K_CARVED_PUMPKIN = registerBlock("uppercase_k_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_L_CARVED_PUMPKIN = registerBlock("uppercase_l_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_M_CARVED_PUMPKIN = registerBlock("uppercase_m_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_N_CARVED_PUMPKIN = registerBlock("uppercase_n_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_O_CARVED_PUMPKIN = registerBlock("uppercase_o_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_P_CARVED_PUMPKIN = registerBlock("uppercase_p_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_Q_CARVED_PUMPKIN = registerBlock("uppercase_q_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_R_CARVED_PUMPKIN = registerBlock("uppercase_r_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_S_CARVED_PUMPKIN = registerBlock("uppercase_s_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_T_CARVED_PUMPKIN = registerBlock("uppercase_t_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_U_CARVED_PUMPKIN = registerBlock("uppercase_u_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_V_CARVED_PUMPKIN = registerBlock("uppercase_v_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_W_CARVED_PUMPKIN = registerBlock("uppercase_w_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_X_CARVED_PUMPKIN = registerBlock("uppercase_x_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_Y_CARVED_PUMPKIN = registerBlock("uppercase_y_carved_pumpkin", createCarvedPumpkin());
        UPPERCASE_Z_CARVED_PUMPKIN = registerBlock("uppercase_z_carved_pumpkin", createCarvedPumpkin());
    }
}
